### 회원가입
POST {{apiAddress}}/join
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}

### login
POST {{apiAddress}}/login
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}

### token check
GET {{apiAddress}}/login-check
Access-Token: {{accessToken}}

### 친구목록 조회
GET {{apiAddress}}/members
Access-Token: {{accessToken}}

### 채팅방 만들기
POST {{apiAddress}}/chats/13
Access-Token: {{accessToken}}

###