### 회원가입
POST {{apiAddress}}/join
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}

###
POST {{apiAddress}}/login
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}

### token check
GET {{apiAddress}}/login-check
Access-Token: {{accessToken}}

### token check - error
GET {{apiAddress}}/login-check

### 친구목록 조회

GET {{apiAddress}}/members
Access-Token: {{accessToken}}

###